config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index" , as: "home"
  namespace :admin do 
    get '/', to: 'posts#index'
    resources :posts
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
	def index
		@posts = Post.all
	end	
	
	def new
		@post = Post.new
	end

	def show
		@post = Post.find(params[:id])
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to admin_post_path(@post)
		end
	end

	def destroy
		@post = Post.find(params[:id])
		if 
			@post.destroy
			redirect_to admin_posts_path
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		@post.update(post_params)
		redirect_to admin_post_path(@post)
	end

	private
	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end	

	def show
		@post = Post.find(params[:id])
	end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/admin-shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark p-4 bg-secondary ">
  <div class="container-fluid d-f d-flex justify-content-around">
    <a class="navbar-brand font-weight-bold" href="#"><%= link_to "Admin Rails App" , admin_path  , {:class => "text-light font-weight-bold"} %></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
		 	    <%= link_to "Main" , home_path , {:class => "p-3"} %>
        </li>

        <li class="nav-item">
          <%= link_to "Create post" , new_admin_post_path , {:class => "p-3"} %>
        </li>

        <% if current_user %>
          <li class="nav-item">
            <%= link_to "Log out" , destroy_user_session_path , method: :delete %>
          </li>

        <% else %> 
        <li class="nav-item">
            <%= link_to "Sign In" , new_user_session_path  %>
        </li>
        
        <li class="nav-item">
         <%= link_to "Registration" ,  new_user_registration_path , {:class => "p-3"}%>
        </li>
        <% end %>
        
      </ul>
    </div>
  </div>
</nav>

app/views/admin/posts/edit.html.erb
<br>
<%= form_for @post do |f| %>
	<%= f.text_field :title %>
	<%= f.text_field :body %>
	<%= f.submit %>
<% end %>

app/views/admin/posts/index.html.erb
<br><%= link_to "Create new posts" , new_admin_post_path  , {:class => "btn btn-outline-warning float-right"}%>
<br><h1>Interesting posts</h1><br>
<% @posts.each do |post| %>
  <p>Name of post - <%= post.title %></p>
  <p>Name of post - <%= post.body %></p>
  <%= link_to "Read more", admin_post_path(post) , {:class => "btn btn-outline-success"}%>
  <hr>
<% end %>

app/views/admin/posts/new.html.erb
<br><h2>Creating Post</h2><br>
<%= form_for [:admin,@post] do |f| %>
	<%= f.text_field :title , {:class => "form-control"} %><br>
	<%= f.text_field :body , {:class => "form-control"} %><br>
	<%= f.submit class: "btn btn-warning"%>
<% end %> 	

app/views/admin/posts/show.html.erb
<h3>Post number - <%= @post.id %></h3><br>
<b>Name - </b><span><%= @post.title %></span><br>
<h4><b>The post - </b><span><%= @post.body %></span></h4>
<hr>
<%= link_to "Edit", edit_admin_post_path(@post) , class: "btn btn-warning" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <% if controller_path =~ /^admin\// %>

      <%= render "admin/admin-shared/header" %>

    <% else %>
      <%= render "shared/header" %>
    <% end %>

    <div class="container"><%= yield %></div>
  </body>
</html>

app/views/posts/index.html.erb
<br><h1>Interesting Posts</h1><br>
<% @posts.each do |post| %>
  <p><b>Name of post -</b> <%= post.title %></p>
  <p><b>Name of post -</b> <%= post.body %></p>
  <hr>
<% end %>

app/views/posts/show.html.erb
<br>
<h5><b>Title -</b> <%= @post.title %></p>
<h5><b>Post -</b> <%= @post.body %></p><br>
<hr><br>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark p-4 bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand font-weight-bold" href="#"><%= link_to "Rails App" , home_path , {:class => "text-light font-weight-bold"} %></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
		 	    <%= link_to "Main" , home_path , {:class => "p-3"} %>
        </li>
      
        <% if current_user %>
          <li class="nav-item">
            <%= link_to "Log out" , destroy_user_session_path , method: :delete %>
          </li>

        <% else %> 
        <li class="nav-item">
            <%= link_to "Sign In" , new_user_session_path  %>
        </li>
        
        <li class="nav-item">
         <%= link_to "Registration" ,  new_user_registration_path , {:class => "p-3"}%>
        </li>
        <% end %>
      
      </ul>
    </div>
  </div>
</nav>